language: java
dist: bionic
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - openjdk8
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - ./gradlew clean build jacocoTestReport jib
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: birthdaygreetingservice